apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns-operator
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - coredns
  verbs:
  - get
  - list
  # TODO: Do we need patch/update this?
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - coredns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - delete
  - patch
  - update
  resourceNames: ["coredns"]
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - delete
  - patch
  - update
  resourceNames: ["coredns"]
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - create
